### ISSUE TITLE
page level styles

### ISSUE THREAD

**Issue by cjessett** [Lapedra/prj-rev-bwfs-dasmoto#3]
(Simplify) [This](https://github.com/Lapedra/prj-rev-bwfs-dasmoto/blob/b9e1b61a844d94e2978db7644c70a79f85ca08b1/Dasmoto%20Arts%20and%20Crafts/resources/css/style.css#L19) and other page level styles can be applied to the `body` tag just once and will be applied to the whole page.

**Comment by Lapedra** [comment]
Totally. Thank you. I realized this after I noticed that I've written 'Helvetica' several times.
